### ISSUE TITLE
BuffedPresents and LethalPresents.

### ISSUE THREAD

**Issue by ElvesLie** [landonk89/Buffed-Presents#1]
Would be nice if there was a way to make both mods compatible with one another, or at least if you added in the same features of LethalPresents into your mod. Thanks :)!

(If you did add in the same features, I might recommend adding in the ability to spawn in the mask itself?)

**Comment by landonk89** [comment]
The mod is fundamentally incompatible with any other mod that patches OpenGiftBoxServerRpc or possibly other methods in the GiftBoxItem class due to the way patching with harmony/bepinex works, there may be ways around this incompatibility but I am not well versed enough in coding yet to do so.
