### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by YuroKashine** [landonk89/Buffed-Presents#3]
Hi,

Im using your mod but it does not work.
Also i dont see any config files for it nor in the configurationmanager mod from BepinEx.
Not sure if its because of lethalpresents but i hope you can find a fix for it!

**Comment by landonk89** [comment]
The mod is fundamentally incompatible with any other mod that patches OpenGiftBoxServerRpc or possibly other methods in the GiftBoxItem class due to the way patching with harmony/bepinex works, there may be ways around this incompatibility but I am not well versed enough in coding yet to do so.
