### ISSUE TITLE
Compat with lethalpresents

### ISSUE THREAD

**Issue by ImpulsiveLass** [landonk89/Buffed-Presents#4]
If lethalpresents is installed, this mod doesn't load.

There really is no reason for this?

this mod affects the drops of presents and their data, lethalpresents just spawns an enemy in addition to the item from the box.

Could you please fix this issue as there doesn't appear to be any reason for it to exist?

**Comment by landonk89** [comment]
When I have a moment I will review the code for LethalPresents in more detail and investigate compatibility, at the time this mod was written I wanted to avoid any compatibility issues, LethalPresents at a quick glance looked like a possible conflict.

**Comment by landonk89** [comment]
I have updated the code to remove the incompatibility and done some basic testing, please see the releases section for the new version 0.0.6.

**Comment by ImpulsiveLass** [comment]
thanks, will check it out, I was told this mod causes incompat because it prefix returns false?
